version: '3.8'

services:
  backend:
    build:
      dockerfile: Dockerfile
      context: ./app
    ports:
      - '3001:3000' # Change the host port if needed
    restart: always
    volumes:
      - ./app:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGODB_URL=mongodb://mongo:27018/mydatabase
      - JWT_SECRET=thisisasamplesecret
      - JWT_ACCESS_EXPIRATION_MINUTES=30
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    ports:
      - '27018:27017'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
